// AUTO-GENERATED by scripts/build-content.js
// Source: content/week-4/
// Do not edit this file directly — edit the .md files instead,
// then run:  node scripts/build-content.js

import type { DayContent } from "./types";

const week_4: DayContent[] = [
  {
    num: 1,
    abbr: "Mon",
    name: "Monday",
    title: `The Gift of Confession`,
    theme: `Confession · The Most Honest Conversation You Can Have`,
    accent: "#3A3580",
    bg: "#EEEEFA",
    verses: [
    {
      label: `Anchor`,
      text: `If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.`,
      ref: `1 John 1:9 — NIV`,
    },
    {
      label: `The Relief of Honesty`,
      text: `Blessed is the one whose transgressions are forgiven, whose sins are covered... When I kept silent, my bones wasted away through my groaning all day long... Then I acknowledged my sin to you and did not cover up my iniquity. I said, 'I will confess my transgressions to the Lord.' And you forgave the guilt of my sin.`,
      ref: `Psalm 32:1, 3, 5 — NIV`,
    },
    {
      label: `The Power of Confession in Community`,
      text: `Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective.`,
      ref: `James 5:16 — NIV`,
    }
    ],
    revelation: [
    `Confession is one of the most countercultural acts a believer can make. In a world that teaches you to manage your image, protect your reputation, and project confidence — God invites you to come with nothing hidden, nothing defended, nothing performed. Confession is not the ritual of a person who has failed. It is the posture of a person who has understood grace. Psalm 32 gives us the anatomy of unconfessed sin — bones wasting away, groaning all day, heaviness that will not lift. David is describing what happens spiritually and even physically when we carry what was never meant to be carried. The burden of hidden sin is enormous. But the moment he opened his mouth to God, the weight lifted. This is not coincidence. It is the design of a God who made us for transparency before Him, not concealment from Him. 1 John 1:9 contains two words that deserve close attention: faithful and just. God does not forgive reluctantly or temporarily. He forgives because it is in His nature. And it is just, because Christ has already paid for every sin you will ever confess. When you confess, you are not asking God to overlook something. You are claiming what was purchased for you at the cross. James 5:16 extends this further — there is healing in confessing to one another. Isolation empowers sin; community disempowers it.`
    ],
    prayers: [
    `Father, I come to You this morning without pretence. I do not come dressed in performance or armed with excuses. I come as I am — with the things I have done that grieve You, the things I have left undone, the thoughts I have entertained, the words I have spoken in anger or pride. I confess them to You now, not because You do not already know, but because confession is my act of agreement with Your truth about me. I agree: I have fallen short. I agree: I need Your mercy. And I receive — with open and grateful hands — the faithfulness and justice of a God who does not hold these things against me because Your Son has already answered for them. Purify me from all unrighteousness. Lift the weight of what I have been carrying. Let this week begin not in the heaviness of unconfessed sin but in the lightness of a soul made clean.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Set aside 15 minutes of honest silence before God. Invite the Holy Spirit to bring to mind anything that needs to be confessed. Write it down. Pray through each one specifically — no vague, general confessions today.`,
    `Read Psalm 32 in full. Sit with the contrast between the heaviness of verses 3–4 and the freedom of verse 5. Let the relief of the Psalmist become your own.`,
    `Consider whether there is someone in your life — a trusted friend, a mentor, a spiritual director — with whom you can practise the honest confession James 5:16 describes. Reach out to them this week.`,
    `Journal: "What have I been carrying in silence that God is inviting me to bring into the light today?" Write freely and honestly.`
    ],
  },

  {
    num: 2,
    abbr: "Tue",
    name: "Tuesday",
    title: `Repentance: More Than Sorry`,
    theme: `Repentance · A Complete Turning of Direction`,
    accent: "#3A3580",
    bg: "#EEEEFA",
    verses: [
    {
      label: `Anchor`,
      text: `Godly sorrow brings repentance that leads to salvation and leaves no regret, but worldly sorrow brings death.`,
      ref: `2 Corinthians 7:10 — NIV`,
    },
    {
      label: `The Promise to the Repentant`,
      text: `Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord.`,
      ref: `Acts 3:19 — NIV`,
    },
    {
      label: `The Posture of Return`,
      text: `When he came to his senses, he said, 'How many of my father's hired servants have food to spare, and here I am starving to death! I will set out and go back to my father.' So he got up and went to his father.`,
      ref: `Luke 15:17–18, 20 — NIV`,
    }
    ],
    revelation: [
    `There is a critical distinction in 2 Corinthians 7:10 that every believer needs to understand. Worldly sorrow says: I feel terrible about what I did. Godly sorrow says: I understand what my sin cost, and I am turning away from it completely. One is a feeling. The other is a decision. Many people confuse emotional regret with genuine repentance — and they wonder why they keep returning to the same sins. The emotion passes, and so does the resolve. The Greek word for repentance is metanoia — literally, a change of mind. But in the Hebrew tradition it carried even richer meaning: shub, to turn, to return. Repentance is not primarily about how you feel about the past. It is about the direction you face going forward. You were walking one way; you stop, turn completely, and walk the other way. The old direction loses its pull not because you are stronger, but because your mind has genuinely changed about where it leads. The prodigal son in Luke 15 gives us the most human portrait of repentance in Scripture. Notice the sequence: he came to his senses, he articulated the truth about his situation, he made a decision, and then — crucially — he got up and went. Repentance that does not move is not yet complete. And when he arrived, his father ran to meet him. This is what waits for you on the other side of genuine repentance: not reluctant acceptance, but a Father running toward you while you are still a long way off.`
    ],
    prayers: [
    `Father, I come to You today not only with words of sorrow but with a turned heart. I do not want to be someone who feels bad and continues unchanged. I want the genuine metanoia — the complete change of mind and direction that Your Word describes. Where I have been walking in the wrong direction — in patterns of thought, habit, relationship, or choice — I stop today. I turn. I face You. And I receive the promise of Acts 3:19: times of refreshing from the Lord. Repentance is not a punishment — it is the doorway to refreshment. I walk through it today. Like the prodigal son, I have come to my senses. I have articulated the truth about where I have been. And now I get up and go to You. Run to me, Father. I am still a long way off — but I am coming.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Luke 15:11–32 in full — the full parable. Identify where you are in the story right now. Are you still in the far country? On the road home? Already at the feast but struggling with the older brother's attitude?`,
    `Journal: "What is the difference between how I have felt sorry in the past and what genuine repentance — a real change of direction — would look like in my specific situation today?"`,
    `Identify one pattern or habit you have been confessing repeatedly without turning from. Ask God specifically for the grace of metanoia — not just sorrow, but a changed mind about where that path leads.`,
    `Read Ezekiel 36:26 — "I will give you a new heart." God does not just forgive the old heart; He replaces it. Receive this promise. Sit with it for five minutes in gratitude.`
    ],
  },

  {
    num: 3,
    abbr: "Wed",
    name: "Wednesday",
    title: `The Call to Holiness`,
    theme: `Holy Living · The Nature of God Pressing Outward`,
    accent: "#1E6060",
    bg: "#E3F5F5",
    verses: [
    {
      label: `Anchor`,
      text: `But just as he who called you is holy, so be holy in all you do; for it is written: 'Be holy, because I am holy.'`,
      ref: `1 Peter 1:15–16 — NIV`,
    },
    {
      label: `Without Holiness`,
      text: `Make every effort to live in peace with everyone and to be holy; without holiness no one will see the Lord.`,
      ref: `Hebrews 12:14 — NIV`,
    },
    {
      label: `The Living Sacrifice`,
      text: `Therefore, I urge you, brothers and sisters, in view of God's mercy, to offer your bodies as a living sacrifice, holy and pleasing to God — this is your true and proper worship. Do not conform to the pattern of this world, but be transformed by the renewing of your mind.`,
      ref: `Romans 12:1–2 — NIV`,
    }
    ],
    revelation: [
    `The command to be holy is the most repeated moral command in all of Scripture. And yet it is perhaps the most misunderstood. For many believers, holiness conjures images of religious restriction — a long list of things you cannot do. But that is not the biblical portrait of holiness. Holiness is not primarily about what you avoid. It is about what you resemble. The root of the Hebrew word for holy — qadosh — means set apart, distinct, other. God is holy not because He follows a set of rules but because He is fundamentally different from everything that is broken, corrupted, or fallen. When He calls you to holiness, He is calling you to resemble Him — to carry something of that otherness into the world. You were not designed to blend in. You were designed to be distinctly, visibly different in a way that points to your Father. Romans 12:1–2 reveals the pathway and the motive. The motive is not fear or obligation — it is mercy. In view of God's mercy, offer yourself. The cross has already been established; holiness is your response to it, not your attempt to earn it. And the pathway is the renewing of your mind — transformation from the inside out. A holy life is not manufactured by willpower. It is grown by dwelling so deeply in God's presence that His nature increasingly becomes yours.`
    ],
    prayers: [
    `Holy Father, Your very name is holiness. And You have called me — not reluctantly, not as a long shot — but intentionally and confidently, to be holy as You are holy. I receive that call today not as a burden but as an invitation into the deepest version of who I was made to be. I offer myself to You this morning as a living sacrifice. Not a dead ritual, not a performance — a living, breathing act of worship in which my body, my mind, my habits, my desires, my relationships, and my time are placed in Your hands. Do with them what only You can do. Renew my mind. Where the patterns of the world have shaped my thinking more than Your Word has, disrupt them. Let the holiness that is already in You — living in me by Your Spirit — press outward and become visible in how I live.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Leviticus 19 — holiness made shockingly practical. Note how many of the commands involve how you treat other people. Holiness is not private; it is relational.`,
    `Identify one area of your life where you have been conforming to the pattern of this world rather than being transformed by the renewing of your mind. Bring it specifically to God today.`,
    `Journal: "What would a holy version of my ordinary week look like? What would change in my habits, my speech, my entertainment, my relationships?"`,
    `Read 1 Thessalonians 4:3–7 and note that God's will for you is your sanctification. It is not ambiguous. Receive the clarity of that today — He has already decided what He wants for you.`
    ],
  },

  {
    num: 4,
    abbr: "Thu",
    name: "Thursday",
    title: `Holiness in the Ordinary`,
    theme: `Holy Living · Every Day, Every Moment, Every Choice`,
    accent: "#1E6060",
    bg: "#E3F5F5",
    verses: [
    {
      label: `Anchor`,
      text: `And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.`,
      ref: `Colossians 3:17 — NIV`,
    },
    {
      label: `The Will of God, Made Plain`,
      text: `It is God's will that you should be sanctified: that you should avoid sexual immorality; that each of you should learn to control your own body in a way that is holy and honourable.`,
      ref: `1 Thessalonians 4:3–4 — NIV`,
    },
    {
      label: `The New Self`,
      text: `You were taught, with regard to your former way of life, to put off your old self, which is being corrupted by its deceitful desires; to be made new in the attitude of your minds; and to put on the new self, created to be like God in true righteousness and holiness.`,
      ref: `Ephesians 4:22–24 — NIV`,
    }
    ],
    revelation: [
    `Yesterday we established the theology of holiness — what it is and why it matters. Today we bring it down to the ground, into the commute, into the conversation, into the screen time, into the small unobserved choices that no one sees but that are the actual substance of a holy life. Colossians 3:17 is one of the most radical verses in the New Testament in its scope: whatever you do — in word or deed — do it in the name of the Lord Jesus. Not just your church activities. Not just your quiet times. Everything. Ephesians 4:22–24 describes holiness as a daily practice of putting off and putting on. The old self — its habits, its reflexes, its patterns — is something you actively, deliberately take off, like a garment. The new self — created to be like God in true righteousness and holiness — is something you actively, deliberately put on. This is not passive waiting for holiness to descend on you. It is daily, intentional cooperation with the work of the Holy Spirit. The word "sanctified" in 1 Thessalonians 4:3 is the same root as holy. God's will for you is your sanctification. Not your success, not your comfort, not your reputation — your becoming more like Him. This reframes every difficulty you face this week. The hard conversation, the temptation resisted, the kindness shown when unkindness would have been easier — these are not interruptions to your spiritual life. They are your spiritual life.`
    ],
    prayers: [
    `Lord, I take off the old self today. Deliberately and intentionally — the impatience, the pride, the careless speech, the habitual compromises I barely notice anymore. I take them off and I lay them down. They are not who I am. They are the residue of who I used to be. And I put on the new self — created to be like You in true righteousness and holiness. I put on gentleness for my interactions today. Integrity for my work. Patience for the frustrations I will encounter. Purity for what I allow through my eyes and my mind. Let everything I do today — every email, every conversation, every decision, every moment of leisure — be done in Your name, as an act of worship. Make my ordinary day holy.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Audit one area of ordinary life — your phone use, your entertainment choices, your speech patterns — through the lens of Colossians 3:17. What would it look like to do that thing in the name of the Lord Jesus?`,
    `Practise the put off / put on discipline from Ephesians 4:22–24 in real time today. When you catch yourself in an old pattern, name it, put it off, and consciously choose the new self response instead.`,
    `Read Colossians 3:5–17 in full — Paul's complete list of what to take off and what to put on. Use it as a practical inventory for your day.`,
    `Journal at the end of the day: "Where did I live in the old self today? Where did I live in the new self? What made the difference between the two?"`
    ],
  },

  {
    num: 5,
    abbr: "Fri",
    name: "Friday",
    title: `God Is Faithful in the Battle`,
    theme: `The Battle · The Armour That Has Already Been Provided`,
    accent: "#8A5A00",
    bg: "#FAF3E8",
    verses: [
    {
      label: `Anchor`,
      text: `Finally, be strong in the Lord and in his mighty power. Put on the full armour of God, so that you can take your stand against the devil's schemes. For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.`,
      ref: `Ephesians 6:10–12 — NIV`,
    },
    {
      label: `The Weapons of Our Warfare`,
      text: `For though we live in the world, we do not wage war as the world does. The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds.`,
      ref: `2 Corinthians 10:3–4 — NIV`,
    },
    {
      label: `No Weapon`,
      text: `No weapon forged against you will prevail, and you will refute every tongue that accuses you. This is the heritage of the servants of the Lord, and this is their vindication from me, declares the Lord.`,
      ref: `Isaiah 54:17 — NIV`,
    }
    ],
    revelation: [
    `One of the enemy's most effective tactics is to convince you that the battles you face are primarily natural — problems of circumstance, personality, finances, relationships. But Ephesians 6 pulls back the curtain. The real war is not against flesh and blood. The people who frustrate you are not your enemy. The systems that oppress you are not the source of the darkness. There is a spiritual reality behind the natural one, and it requires a different kind of weapon. Notice that Paul says put on the full armour of God — not armour you manufacture, not strength you generate, but armour that belongs to God and is offered to you. Every piece of this armour is something Christ has already secured. The righteousness that protects your heart is His. The truth that stabilises you is His Word. You are not fighting for protection — you are stepping into protection that already exists. Isaiah 54:17 is a declaration of heritage, not a request. No weapon forged against you will prevail. This is the inheritance of the servants of the Lord. You do not fight to achieve victory — you fight from a position of victory that was secured at the cross and confirmed at the resurrection. The battle is real. The opposition is real. But the outcome is already determined. Stand firm, knowing that the One who is in you is greater than the one who is in the world.`
    ],
    prayers: [
    `Lord of Hosts, I acknowledge today that I am in a battle — not with people, not with circumstances, but with spiritual forces that want to derail the work You are doing in me. I do not face this in my own strength. But I face it in Yours — and in You, I cannot be defeated. I put on the full armour of God today. I fasten the belt of truth — let Your Word be the foundation of everything I think and say. I put on the breastplate of righteousness — let Christ's righteousness, not my own performance, be my protection. I take up the shield of faith — every lie of the enemy is extinguished by my trust in You. And I declare over every battle I am currently facing: no weapon forged against me will prevail. Not the accusation, not the opposition, not the discouragement, not the setback. This is my heritage as Your servant.`
    ],
    amen: `In the mighty name of Jesus, Amen.`,
    practices: [
    `Read Ephesians 6:10–18 in full. Go through each piece of armour deliberately — what it protects you from and how you put it on practically today. Make it specific, not theoretical.`,
    `Identify the primary battle you are facing this season. Name it clearly. Then ask: is this a battle against flesh and blood, or is there a spiritual dimension I have been ignoring?`,
    `Read 1 John 4:4 — "Greater is He who is in you than he who is in the world." Memorise it. Speak it aloud three times as a declaration over your situation today.`,
    `Spend 10 minutes in targeted intercessory prayer — not general prayer, but specific spiritual warfare prayer over the battles you named above. Pray with authority and confidence, from the position of victory.`
    ],
  },

  {
    num: 6,
    abbr: "Sat",
    name: "Saturday",
    title: `Trusting God When You Cannot See`,
    theme: `Trust · Anchored to His Faithfulness, Not Your Circumstances`,
    accent: "#BF8B3A",
    bg: "#FAF3E0",
    verses: [
    {
      label: `Anchor`,
      text: `Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.`,
      ref: `Proverbs 3:5–6 — NIV`,
    },
    {
      label: `All Things Working`,
      text: `And we know that in all things God works for the good of those who love him, who have been called according to his purpose.`,
      ref: `Romans 8:28 — NIV`,
    },
    {
      label: `Praise Before the Harvest`,
      text: `Though the fig tree does not bud and there are no grapes on the vines, though the olive crop fails and the fields produce no food, though there are no sheep in the pen and no cattle in the stalls, yet I will rejoice in the Lord, I will be joyful in God my Saviour.`,
      ref: `Habakkuk 3:17–18 — NIV`,
    }
    ],
    revelation: [
    `Habakkuk 3:17–18 is perhaps the most audacious act of trust in all of Scripture. The prophet is not describing a season of abundance and then praising God for it. He is standing in the middle of total collapse — no figs, no grapes, no olives, no sheep, no cattle — and choosing joy. This is not denial. Habakkuk sees the emptiness clearly. He lists it precisely, item by item. And then he says: yet. That single word carries the full weight of a faith that has learned to rest in the character of God when the circumstances offer nothing to stand on. Proverbs 3:5–6 gives us the anatomy of this kind of trust. With all your heart — not partial trust, not cautious optimism, not "I'll trust God but keep my own backup plan." All. And lean not on your own understanding — your analysis of the situation, however accurate, is partial. God's vision includes dimensions you cannot see from where you are standing. Trust does not require you to stop thinking. It requires you to hold your conclusions loosely, in submission to a God whose wisdom is higher than yours. Romans 8:28 carries an active verb that is easy to miss: God works. He is not passively allowing your suffering. He is actively, sovereignly, continuously weaving every circumstance — including the painful ones, the confusing ones, the ones that seem like waste — into something redemptive. You cannot always see the weaving from the inside of the tapestry. But He sees it from above. And He has not stopped working.`
    ],
    prayers: [
    `Father, I bring You today the circumstances that make trust most difficult — the unanswered prayers, the unresolved situations, the things that still look like empty fields and bare vines. I do not pretend they are not there. I see them clearly. And yet. Yet I will rejoice in the Lord. Not because the circumstances have changed — they have not. But because You have not changed. You are still faithful. You are still working. You are still weaving things I cannot see into something I will one day marvel at. My trust is not in my ability to understand what You are doing. My trust is in the character of the One who is doing it. I lean not on my own understanding today. I hold my plans, my analysis, my timelines, and my expectations loosely — and I submit them to You. Make my paths straight, Lord.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Habakkuk 3:1–19 in full — the full arc of the prophet's journey from complaint to confident trust. Let his progression become yours. Note what changed in him before anything changed in his circumstances.`,
    `Write down your "empty fields" — the specific circumstances where trust is hardest right now. Then write Romans 8:28 beneath each one. God is actively working in these too.`,
    `Practise the "yet I will rejoice" discipline today. Before any circumstances change, choose one act of deliberate worship — a song, a prayer of gratitude, a declaration. Not for the circumstances, but for who God is in them.`,
    `Read Genesis 50:20 — Joseph's summary of his life: "You intended to harm me, but God intended it for good." Think of one past situation where you can now see God's weaving. Let it build your faith for where you are now.`
    ],
  },

  {
    num: 7,
    abbr: "Sun",
    name: "Sunday",
    title: `The Overcomer's Rest`,
    theme: `Victory · Not Fighting for It — Resting in It`,
    accent: "#BF8B3A",
    bg: "#FAF3E0",
    verses: [
    {
      label: `Anchor`,
      text: `They triumphed over him by the blood of the Lamb and by the word of their testimony; they did not love their lives so much as to shrink from death.`,
      ref: `Revelation 12:11 — NIV`,
    },
    {
      label: `More Than Conquerors`,
      text: `No, in all these things we are more than conquerors through him who loved us.`,
      ref: `Romans 8:37 — NIV`,
    },
    {
      label: `Peace Already Given`,
      text: `I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.`,
      ref: `John 16:33 — NIV`,
    }
    ],
    revelation: [
    `The week closes not in exhaustion but in rest — the particular, hard-won rest of someone who has confessed honestly, repented genuinely, chosen holiness daily, armed themselves for battle, and learned to trust in the dark. This is not the rest of someone who has avoided the fight. It is the rest of someone who has been in it and discovered that the One fighting alongside them cannot lose. Revelation 12:11 reveals the weapons of the overcomer: the blood of the Lamb and the word of their testimony. You overcome not by being stronger than the enemy but by being covered by what Christ did. His blood — the finished work of the cross — is your legal basis for every victory. And your testimony — what God has done in your life — is a weapon, because it declares in real and personal terms that God is faithful. Your story of God's faithfulness is not just comfort for yourself. It is a weapon against the darkness. John 16:33 contains perhaps the most honest and yet most reassuring promise in the Gospels. Jesus does not promise you a life without trouble. He says plainly: in this world you will have trouble. But then — But take heart! I have overcome the world. He has already overcome the very world that is troubling you. The battles are real. The challenges are real. But the verdict is already in. You are more than a conqueror — not because you are fighting hard enough, but because you are in Christ, and in Christ the victory is settled, permanent, and yours.`
    ],
    prayers: [
    `Father, I close this week in a posture of rest — not because everything is resolved, but because I know the One in whom all things are resolved. I have confessed what needed to be brought into the light. I have turned from what needed to be left behind. I have chosen holiness not as a burden but as a way of life. I have put on Your armour. I have trusted You in the dark. And now I rest. Not the rest of the passive or the defeated, but the rest of the overcomer — the one who has fought from a position of victory and returned to that place of peace. The blood of the Lamb covers me. My testimony speaks of Your faithfulness. The world that troubles me has already been overcome by the One who lives in me. Send me into the coming week as a person who knows they cannot be ultimately defeated. Not because my circumstances are favourable, but because You have overcome.`
    ],
    amen: `In the triumphant name of Jesus Christ, Amen.`,
    practices: [
    `Review the whole week — which theme landed most deeply? Confession, repentance, holiness, warfare, or trust? Write one sentence that captures what God said to you through that theme. Carry it forward.`,
    `Share one insight from this week with someone in your life — a friend, a partner, a member of your faith community. Your testimony is a weapon. Use it deliberately.`,
    `Identify one concrete change — in habit, in practice, in posture before God — that you are committing to carry forward from this week into the next. Be specific, not vague.`,
    `Read Romans 8:31–39 as your closing declaration. Let Paul's unanswerable questions be your war cry: If God is for us, who can be against us?`
    ],
  },
];

export default week_4;
