// AUTO-GENERATED by scripts/build-content.js
// Source: content/week-8/
// Do not edit this file directly — edit the .md files instead,
// then run:  node scripts/build-content.js

import type { DayContent } from "./types";

const week_8: DayContent[] = [
  {
    num: 1,
    abbr: "Mon",
    name: "Monday",
    title: `When the Walls Are Closing In`,
    theme: `Trusting God in Crisis · Hezekiah and the Letter`,
    accent: "#2C3E5A",
    bg: "#EEF2F7",
    verses: [
    {
      label: `Anchor`,
      text: `Hezekiah received the letter from the messengers and read it. Then he went up to the temple of the Lord and spread it out before the Lord. And Hezekiah prayed to the Lord: 'Lord Almighty, the God of Israel, enthroned between the cherubim, you alone are God over all the kingdoms of the earth. You have made heaven and earth.'`,
      ref: `Isaiah 37:14–15 — NIV`,
    },
    {
      label: `God Is Our Refuge`,
      text: `God is our refuge and strength, an ever-present help in trouble. Therefore we will not fear, though the earth give way and the mountains fall into the heart of the sea.`,
      ref: `Psalm 46:1–2 — NIV`,
    },
    {
      label: `The Posture of Trust`,
      text: `Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.`,
      ref: `Proverbs 3:5–6 — NIV`,
    }
    ],
    revelation: [
    `The year is 701 BC. Sennacherib, king of Assyria, has already swallowed every nation in his path. His army is the most feared military force the ancient world has ever seen. And now the letter arrives — a piece of correspondence designed not merely to threaten but to psychologically destroy. It lists every nation that has already fallen. It asks the question with cold logic: what makes you think your God is any different from the gods of the nations I have already destroyed? It is the most sophisticated crisis Hezekiah has ever faced, and there is no military answer, no political solution, no human path through it.`,
    `What Hezekiah does next is one of the most instructive moments in the entire Old Testament. He does not call a war council. He does not draft a diplomatic response. He does not collapse in despair. He takes the letter — this physical object that represents the full weight of his crisis — and he walks up to the temple, and he spreads it out before God. That act is worth sitting with for a long time. He did not summarise the problem. He did not give God a bullet-pointed briefing. He unfolded the letter and laid it down, as if to say: You see this. You read it. Now respond. There is a profound theological confidence in that act. Hezekiah believed that God could read his mail. He believed that the details of his crisis were not beneath God's attention. He believed that the same God who made heaven and earth was interested in one king's specific impossible situation.`,
    `This is the invitation the crisis is bringing to you today. Not to pretend the letter does not exist. Not to spiritualise it away. But to take the actual, specific, documented weight of what you are facing — and spread it out before God. The crisis is not evidence that God is absent. It is the very circumstance that reveals whether your trust is real. Hezekiah's trust was not a pleasant spiritual feeling he had during calm seasons. It was a decision he made when the walls were closing in. That is the only kind of trust that means anything.`
    ],
    prayers: [
    `Lord God, I come to You this morning the way Hezekiah came — with the letter in my hand. The specific thing that is pressing on me, the situation that has no visible solution, the fear that surfaces in the night when I cannot distract myself from it. I do not come with a tidy summary. I spread it out before You. You see it. You know every detail. And I trust that the God who made heaven and earth is not overwhelmed by what is overwhelming me.`,
    `I confess that my first instinct in crisis is often not prayer. It is strategy, or worry, or the desperate search for a human solution. Forgive me for treating prayer as a last resort when it is the most powerful first move available. I choose today to begin where Hezekiah began — in the temple, before You, with the impossible thing fully acknowledged and fully submitted.`,
    `You are God over all the kingdoms of the earth. You are God over this situation. I trust You not because the outcome is already clear but because You are already here — present, attentive, and more than sufficient for everything I am carrying.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Isaiah 37:1–20 in full — the complete account of Hezekiah's crisis and prayer. Note every specific detail of what he did before he prayed, how he prayed, and what he asked God to do. Let his posture become a model for your own.`,
    `Take the specific crisis or pressure you are currently carrying and write it down in full — every detail, as if writing the letter Hezekiah received. Then physically place your hand on the paper and pray over it. Let the act of spreading it before God be as deliberate as Hezekiah's was.`,
    `Journal: "What is my instinctive first response when crisis arrives — strategy, worry, or prayer? What would it look like for prayer to become genuinely first, not last?" Be honest rather than aspirational.`,
    `Read Psalm 46 in full as your declaration for today. Note especially verse 10 — "Be still and know that I am God." In the middle of the crisis, stillness is not passivity. It is the most radical act of trust available to you.`
    ],
  },

  {
    num: 2,
    abbr: "Tue",
    name: "Tuesday",
    title: `God Answers the Unanswerable`,
    theme: `Trusting God in Crisis · The Deliverance Only God Could Give`,
    accent: "#2C3E5A",
    bg: "#EEF2F7",
    verses: [
    {
      label: `Anchor`,
      text: `Therefore this is what the Lord says concerning the king of Assyria: He will not enter this city or shoot an arrow here... By the way that he came he will return; he will not enter this city, declares the Lord. I will defend this city and save it, for my sake and for the sake of David my servant.`,
      ref: `Isaiah 37:33–35 — NIV`,
    },
    {
      label: `The Lord Will Fight For You`,
      text: `Moses answered the people, 'Do not be afraid. Stand firm and you will see the deliverance the Lord will bring you today. The Egyptians you see today you will never see again. The Lord will fight for you; you need only to be still.'`,
      ref: `Exodus 14:13–14 — NIV`,
    },
    {
      label: `If God Is For Us`,
      text: `What, then, shall we say in response to these things? If God is for us, who can be against us?`,
      ref: `Romans 8:31 — NIV`,
    }
    ],
    revelation: [
    `The morning after Hezekiah's prayer, 185,000 Assyrian soldiers were dead. The text is almost casual in its brevity: "When the people got up the next morning — there were all the dead bodies." No battle. No heroism. No last-minute human ingenuity. Hezekiah did not go to sleep having solved the crisis. He went to sleep having surrendered it. And while he slept, God worked. The crisis that had no human answer received a divine one — overnight, silently, completely.`,
    `This is the pattern Scripture keeps returning to with almost stubborn repetition. At the Red Sea, Israel was trapped — sea in front, Egyptian army behind, no escape route. Moses said the words that deserve to be carved above every crisis you will ever face: the Lord will fight for you; you need only to be still. Not "figure it out." Not "try harder." Not "find a cleverer strategy." Be still. The deliverance God brings is often of a quality that makes it unmistakably His — precisely because it could not have come any other way. If Hezekiah had found a military solution, the story would have been about Hezekiah's tactics. Because there was no human solution, the story is about God's power. The impossibility was not an obstacle to God's glory. It was the very vehicle for it.`,
    `Romans 8:31 asks a question that is not rhetorical — it demands an answer. If God is for us, who can be against us? The logic is airtight. Whatever stands against you in this season, however real and however powerful, exists in a universe in which God has declared Himself to be on your side. Sennacherib's 185,000 soldiers were objectively more powerful than Hezekiah's army. They were not more powerful than Hezekiah's God. The same arithmetic applies to your situation. The opposition is real. The opposition is not ultimate. The God who answered the unanswerable for Hezekiah has not retired.`
    ],
    prayers: [
    `Father, I receive today the testimony of Hezekiah's morning — the morning when he woke up and found that the crisis that had seemed insurmountable had been resolved while he slept, by a power that had no need of his involvement. I receive that not as a distant historical story but as a declaration of who You are. You are still that God. You still fight for those who trust You. You still answer the unanswerable.`,
    `I release my grip today on the outcome of the impossible things I am carrying. I have been trying to figure out how You will resolve them, which is not my job. My job is to trust and to be still. The resolution is Yours. The timing is Yours. The method is Yours. I choose today to stop advising You on how to do it and simply trust that You will.`,
    `Let the testimony of the 185,000 be living faith in me — not just historical information, but present confidence. If You did it then, You can do it now. You are the same yesterday, today, and forever. I will not be afraid.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Isaiah 37:21–38 in full — God's response to Hezekiah's prayer and the outcome. Note the specific language God uses about Sennacherib and about His own name. The deliverance was as much about God's reputation as it was about Hezekiah's safety.`,
    `Read Exodus 14:10–31 in full — the Red Sea crossing. Count how many times the people were afraid, how many times Moses called them to trust, and the quality of the deliverance they experienced. Let their story build your faith for your own.`,
    `Journal: "What is the impossible situation in my life that I have been trying to solve instead of surrender? What would it practically look like to release the outcome to God today, specifically?" Write a prayer of surrender over it.`,
    `Speak Romans 8:31–39 aloud as a declaration. Every verse is a statement of war against fear and despair. Let the cumulative weight of Paul's argument land fully before you move on with your day.`
    ],
  },

  {
    num: 3,
    abbr: "Wed",
    name: "Wednesday",
    title: `The Hidden Hand: God's Providence in the Ordinary`,
    theme: `Ruth and Hesed · When God Works Without Announcing Himself`,
    accent: "#2E6B50",
    bg: "#EBF5EF",
    verses: [
    {
      label: `Anchor`,
      text: `'The Lord bless him!' Naomi said to her daughter-in-law. 'He has not stopped showing his kindness to the living and the dead.' She added, 'That man is our close relative; he is one of our guardian-redeemers.'`,
      ref: `Ruth 2:20 — NIV`,
    },
    {
      label: `The Covenant of Loyalty`,
      text: `But Ruth replied, 'Don't urge me to leave you or to turn back from you. Where you go I will go, and where you stay I will stay. Your people shall be my people and your God my God.'`,
      ref: `Ruth 1:16 — NIV`,
    },
    {
      label: `Acknowledged in All Your Ways`,
      text: `In all your ways acknowledge him, and he will make your paths straight.`,
      ref: `Proverbs 3:6 — NIV`,
    }
    ],
    revelation: [
    `The book of Ruth contains no miracles. No angel appears. No sea parts. No fire falls from heaven. No voice speaks from a cloud. And yet it is one of the most theologically rich books in the entire Bible precisely because of what it shows us about how God most commonly works — not through the spectacular, but through the faithful, ordinary choices of people who love Him and love others, quietly, without fanfare, in the middle of very difficult circumstances.`,
    `Naomi has lost everything. Her husband, her sons, her country, her future. She is returning to Bethlehem as a widow, a foreigner's widow at her side, with nothing to recommend her situation to anyone paying attention. And then Ruth goes to glean in a field. And she happens to be in the portion belonging to Boaz. And Boaz happens to notice her. And he happens to be a kinsman-redeemer. Every "happens" in that sentence is the hidden hand of God. The providence of God in the book of Ruth works entirely through ordinary human decisions — Ruth's loyalty, Boaz's kindness, Naomi's wisdom — and yet looking back across the whole story, it is unmistakably God at every point. The randomness was not random. The coincidence was not coincidence. The field Ruth chose to glean in was the field she was supposed to be in.`,
    `This is how God most often works in your life too. Not with dramatic interruptions but with a quiet, invisible sovereignty that is weaving your faithful, ordinary choices into something you will only be able to see in its fullness when you look back. The loyalty you are showing today, the kindness you are extending in a season when you have little to give, the faithfulness you are maintaining in a role that no one is watching — these are not neutral. They are the very substance through which God is working out His providential purposes in your story. You do not need to see the whole picture. You need to be faithful in the portion of the field where He has placed you today.`
    ],
    prayers: [
    `Father, I thank You today for the book of Ruth — for the evidence it gives that You are just as present and just as sovereign in the unspectacular, difficult, ordinary seasons as You are in the dramatic ones. I confess that I have sometimes measured Your presence by the intensity of the experience, and found myself wondering if You were there in the quiet, unremarkable days when nothing seemed to be happening. Ruth teaches me: You are there. You are always there. The ordinary is Your ordinary workspace.`,
    `Help me to be faithful today in the small things — the small acts of loyalty, the small choices of kindness, the small decisions of integrity that no one will notice but You. Let me trust that these are not inconsequential. Let me trust that the field I am in today is the field You have placed me in, and that You are already working in ways I cannot yet see.`,
    `Where I am tempted to wait for the big moment before I give my best, correct me. The big moment is built from the ordinary ones. Ruth's faithfulness in the small choice to stay produced a harvest she could not have imagined on the road from Moab. Let my faithfulness today be the seed of something I cannot yet see.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read the entire book of Ruth in one sitting — it is only four chapters and takes about fifteen minutes. Read it looking specifically for the moments where God's hand is visible but never announced. Count how many ordinary human choices ended up being providentially significant.`,
    `Journal: "Where in my own story can I now see, looking back, that what felt like coincidence or accident was actually God's providence at work?" Write the story of one such moment in full. Let it build your faith for the present.`,
    `Identify one specific act of faithful loyalty or kindness you can show today to someone in your life who is in a difficult season — the equivalent of Boaz noticing Ruth and leaving grain in her path deliberately. Do it without telling anyone.`,
    `Read Proverbs 3:1–12 in full as a meditation on what it looks like to walk in the kind of faithfulness that God works through. Note the pattern: here is how to live, and here is what God does in response. Let the pattern shape your day.`
    ],
  },

  {
    num: 4,
    abbr: "Thu",
    name: "Thursday",
    title: `Hesed: The Love That Does Not Let Go`,
    theme: `Covenant Faithfulness · The Character of God and the Calling of His People`,
    accent: "#2E6B50",
    bg: "#EBF5EF",
    verses: [
    {
      label: `Anchor`,
      text: `'The Lord bless you, my daughter,' he replied. 'This kindness is greater than that which you showed earlier: You have not run after the younger men, whether rich or poor. And now, my daughter, don't be afraid. I will do for you all you ask.'`,
      ref: `Ruth 3:10–11a — NIV`,
    },
    {
      label: `New Every Morning`,
      text: `Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.`,
      ref: `Lamentations 3:22–23 — NIV`,
    },
    {
      label: `What the Lord Requires`,
      text: `He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.`,
      ref: `Micah 6:8 — NIV`,
    }
    ],
    revelation: [
    `The Hebrew word hesed is one of the richest and most untranslatable words in the entire Bible. English translations rotate through "kindness," "mercy," "steadfast love," "loyal love," and "loving-kindness" — and none of them fully captures it. Hesed is the love that persists beyond what is required. It is the love that stays when every obligation has been satisfied and the person could reasonably leave. It is the love that shows up in the small, practical, costly details of another person's life and keeps showing up, not because the relationship demands it, but because the character of the lover cannot do otherwise.`,
    `Boaz uses the word about Ruth. He says: this hesed you are showing — this loyalty, this kindness, this covenant faithfulness to Naomi — is greater than what you showed before. He is saying: I see the quality of your love. It is not ordinary love. It is the kind of love that does not run after easier options. And in that moment, a Moabite widow gleaning in a field becomes one of the most precise human portraits of the character of God in the entire Old Testament. Because hesed is, above all, a word about God. Lamentations 3:22 says His hesed never fails. Every morning it is renewed. It did not fail when Israel was faithless. It did not fail in the exile. It does not fail in your worst season.`,
    `Micah 6:8 tells us that loving hesed is not optional for those who have received it. To love mercy, to practice hesed — this is what God requires. Not the performance of religion, not the accumulation of correct doctrine, but the lived, practical, costly, persisting love toward other people that looks like what God has shown to us. Ruth did not receive hesed in a theoretical form — she received it through Naomi's testimony, through Boaz's grain, through God's quiet orchestration of a story that ended in redemption. And she became a conduit of it herself. This is how hesed works: it is received, and then it flows.`
    ],
    prayers: [
    `Father, I sit today with this word — hesed — and I receive it as a description of You. Your love for me is not the love of obligation. It is not the love of a God who stays because He has no better options. It is the love of a God whose character is covenant faithfulness, whose nature is to persist, whose hesed is new every single morning without exception and without diminishment.`,
    `Where I have loved people with conditional love — the love that stays only as long as it is reciprocated, that gives only when it is comfortable, that shows up only when the cost is manageable — convict me and change me. Let the hesed I have received from You become the hesed I extend to others. Let me be someone who does not run after easier options when the loyal, faithful, costly thing is available.`,
    `And in the places where I feel that Your love might have finally run out — where my failures are so consistent, my wandering so repeated, that I cannot quite believe the hesed is still new this morning — let the testimony of Lamentations 3 and Ruth and the whole arc of Scripture be louder than that voice. Your compassions never fail. Great is Your faithfulness. I receive that today.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Ruth chapters 2 and 3 specifically with the lens of hesed — noting every moment where this quality appears in Ruth's choices, in Boaz's responses, and in Naomi's commentary. See if you can identify how many times it surfaces across just these two chapters.`,
    `Look up and read these four passages side by side: Exodus 34:6–7, Psalm 136 (the whole psalm), Lamentations 3:19–33, and Hosea 2:19–20. Each one is a different facet of God's hesed. Journal what each one adds to your understanding.`,
    `Identify one relationship in your life that currently requires hesed from you — the kind of faithful, costly, persisting love that does not run after easier options. Name it specifically. Pray over it. Ask God to give you the capacity to love that person the way He loves you.`,
    `Practise hesed in one concrete act today — not a grand gesture, a small and deliberate one. Leave the equivalent of grain in someone's path. Do it quietly and do not tell anyone.`
    ],
  },

  {
    num: 5,
    abbr: "Fri",
    name: "Friday",
    title: `The Prayer That Moves Heaven`,
    theme: `The Power of Prayer · Hezekiah, Daniel, and the Pattern of Those Who Prevailed`,
    accent: "#7A1A1A",
    bg: "#FAF0F0",
    verses: [
    {
      label: `Anchor`,
      text: `Now when Daniel learned that the decree had been published, he went home to his upstairs room where the windows opened toward Jerusalem. Three times a day he got down on his knees and prayed, giving thanks to his God, just as he had done before.`,
      ref: `Daniel 6:10 — NIV`,
    },
    {
      label: `Intercession with Fasting`,
      text: `So I turned to the Lord God and pleaded with him in prayer and petition, in fasting, and in sackcloth and ashes. I prayed to the Lord my God and confessed: 'Lord, the great and awesome God, who keeps his covenant of love with all who love him and keep his commandments, we have sinned and done wrong.'`,
      ref: `Daniel 9:3–5 — NIV`,
    },
    {
      label: `The Condition of Answered Prayer`,
      text: `If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land.`,
      ref: `2 Chronicles 7:14 — NIV`,
    }
    ],
    revelation: [
    `Daniel knew the decree. He knew that praying to anyone other than the king was punishable by death in the lions' den. He had read the document. He understood the legal reality. And then he went upstairs, opened his windows toward Jerusalem, got on his knees, and prayed — exactly as he had always done. Three times a day. As he had done before. This is the detail that should stop you entirely. Daniel's response to the most dangerous crisis of his career was not a new prayer strategy. It was the same prayer discipline he had always had. He did not pray more dramatically because the stakes were higher. He prayed exactly as he had always prayed — faithfully, consistently, without performance — because that was who he was. The crisis did not create his prayer life. His prayer life had been created long before the crisis, so that when the crisis came, he was already exactly where he needed to be.`,
    `Hezekiah spread his letter before God. Daniel opened his windows toward Jerusalem. Both men oriented their physical bodies toward God in the middle of their impossible situations. Both were men whose prayer was not a technique they deployed in emergencies but a relationship they inhabited daily. And 2 Chronicles 7:14 shows us the full architecture of the kind of prayer that moves heaven — humility, seeking, turning. Not eloquence. Not volume. Not the right formula. The posture of a people who have acknowledged that they need God more than they need anything else.`,
    `Daniel 9 shows us the depth of Daniel's intercession — he is not praying for himself, he is standing in the gap for an entire people, confessing sins that were not primarily his own, pleading on the basis of God's character and God's name rather than his own righteousness. This is what mature prayer looks like. It is not merely petition — tell God what I need. It is intercession — standing between God and the people or situations He has placed on your heart, bearing their weight, refusing to let go until heaven responds. The prayers that moved heaven in Scripture were not the loudest ones. They were the most faithful, the most persistent, and the most deeply oriented toward God's glory rather than the pray-er's comfort.`
    ],
    prayers: [
    `Father, I come to You today convicted by Daniel's windows. He opened them toward Jerusalem not because it was safe but because it was true — prayer was not a compartment of his life, it was the orientation of his life. I want to be that kind of person. Not someone who prays when the stakes are high enough to force me to, but someone whose whole life is turned toward You so consistently that prayer in crisis is simply an intensification of what was already happening.`,
    `Teach me the discipline of Daniel — faithful, unhurried, unperformed, three-times-daily communion with You that is not dependent on how I feel or what the circumstances are requiring of me. Teach me the intercession of Daniel 9 — the willingness to stand in the gap for others, to carry burdens that are not my own, to pray for people and situations that cost me something to hold before You.`,
    `And let my prayer be shaped by 2 Chronicles 7:14 — humility, seeking, turning. Not the eloquence of my words but the orientation of my heart. Hear from heaven, Lord. Forgive. Heal. I ask not on the basis of my track record but on the basis of Your character and Your covenant. Your name is at stake in my situation. Let Your name be glorified through how You answer.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Daniel 6 in full — the lions' den account. Focus specifically on verse 10 and the phrase "just as he had done before." Ask yourself: what is the "just as I had done before" of my own prayer life? What consistent disciplines do I have that would sustain me in a crisis?`,
    `Read Daniel 9:1–19 in full — one of the greatest intercessory prayers in Scripture. Note the structure: it begins with God's character, moves through honest confession, and ends with petition based entirely on God's name and God's mercy rather than Daniel's righteousness.`,
    `Set three prayer times for today — morning, midday, evening — and keep all three, even briefly. Not as a permanent new rule but as an experience of what Daniel's three-times-daily discipline felt like. Journal what the midday and evening prayers were like compared to the morning one.`,
    `Read 2 Chronicles 7:11–16 in full for the context of verse 14. Note that God is describing what to do when things have gone wrong — when the land is in drought, plague, or crisis. The prescription is always the same: turn toward God. Let this shape how you respond the next time a crisis arrives.`
    ],
  },

  {
    num: 6,
    abbr: "Sat",
    name: "Saturday",
    title: `Waiting Well: Righteousness as the Posture of Advent`,
    theme: `Waiting for the Messiah · The Discipline of Holy Expectation`,
    accent: "#BF8B3A",
    bg: "#FAF3E0",
    verses: [
    {
      label: `Anchor`,
      text: `Now there was a man in Jerusalem called Simeon, who was righteous and devout. He was waiting for the consolation of Israel, and the Holy Spirit was on him. It had been revealed to him by the Holy Spirit that he would not die before he had seen the Lord's Messiah.`,
      ref: `Luke 2:25–26 — NIV`,
    },
    {
      label: `Anna's Faithfulness`,
      text: `There was also a prophet, Anna, the daughter of Penuel, of the tribe of Asher. She was very old... She never left the temple but worshipped night and day, fasting and praying. Coming up to them at that very moment, she gave thanks to God and spoke about the child to all who were looking forward to the redemption of Jerusalem.`,
      ref: `Luke 2:36–38 — NIV`,
    },
    {
      label: `Waiting With Hope`,
      text: `But as for me, I watch in hope for the Lord, I wait for God my Saviour; my God will hear me.`,
      ref: `Micah 7:7 — NIV`,
    }
    ],
    revelation: [
    `Between the last word of Malachi and the first word of Matthew, there are four hundred years of silence. No prophet spoke. No new Scripture was written. The last thing God said through Malachi was: I will send the prophet Elijah before the great and dreadful day of the Lord comes. And then — nothing. Four hundred years of nothing. And yet in those four hundred years, there were people who did not stop waiting. People who did not interpret the silence as abandonment. People who kept the faith with extraordinary faithfulness through generations that never saw the fulfilment of what they were waiting for.`,
    `Simeon is one of the most moving figures in the entire New Testament. Luke tells us he was righteous and devout — these are not casual adjectives. They describe the shape of a life, the accumulated character of decades of faithful living. He was waiting for the consolation of Israel. That waiting was not passive. It was not the waiting of someone parked in neutral, not really living, just holding on until the thing they are waiting for arrives. Simeon's waiting was active — expressed in righteousness, in devotion, in a lifestyle shaped by the promise he was holding. He had been told he would not die before he saw the Messiah, and rather than that promise making him passive, it made him more alive, more attentive, more shaped by holy expectation.`,
    `Anna had been in the temple worshipping night and day for decades. She was a widow of eighty-four years who had outlasted her grief and transformed it into intercession. These two people — an old man and an elderly widow — represent the faithful remnant of Israel. The anawim. The poor in spirit who had nothing left to hold onto except the promise of God. And they were the ones who were present when the promise walked through the door. Their waiting had not been wasted. Every decade of faithfulness, every night of prayer, every day of righteous living had been preparation for the moment when they would hold the consolation of Israel in their arms. Waiting well is not time wasted. It is time invested in becoming the person who is ready to receive what is coming.`
    ],
    prayers: [
    `Father, I sit today with Simeon and Anna — two people who waited a very long time for something they had been promised, and who waited well. I want to be that kind of person. Not someone who waits with impatience and resentment, measuring the distance between the promise and its fulfilment with increasing frustration. Someone who waits with righteousness and devotion, whose daily faithfulness is itself a form of worship, whose whole life is shaped by the confidence that what You have promised will arrive.`,
    `I confess that I find waiting difficult. I am more comfortable with resolution than with process, more comfortable with answers than with the long faithfulness of living in the question. Teach me the patience of Simeon. Teach me the devotion of Anna. Let the waiting season I am in — whatever it is, wherever I am between promise and fulfilment — be a season of becoming rather than merely enduring.`,
    `And let my waiting be shaped by holy living. The Messiah is coming — He came, and He is coming again. Let the way I live this week be the way someone lives who genuinely believes that. Not someone performing religion, but someone shaped from the inside out by the expectation of His return.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Luke 2:22–38 in full — both Simeon's song and Anna's response. Sit with the quality of their encounter with the infant Jesus. These were people whose long faithfulness had made them exquisitely sensitive to the presence of God. Ask: what is my waiting producing in me — bitterness or sensitivity?`,
    `Read Lamentations 3:25–26 — "The Lord is good to those whose hope is in him, to the one who seeks him; it is good to wait quietly for the salvation of the Lord." Meditate on the phrase "wait quietly." What would quiet, faithful, undramatic waiting look like in your specific situation today?`,
    `Journal: "What am I currently waiting for that God has promised? How am I waiting — actively or passively, hopefully or resentfully, in righteousness or in spiritual drift?" Let the answer be honest before it is aspirational.`,
    `Read Isaiah 40:28–31 as your closing meditation — the classic passage on waiting for the Lord and the renewal of strength. Let "those who wait upon the Lord shall renew their strength" be your declaration for whatever waiting season you are currently in.`
    ],
  },

  {
    num: 7,
    abbr: "Sun",
    name: "Sunday",
    title: `Maranatha: Come, Lord Jesus`,
    theme: `The Week's Culmination · Living Between the Already and the Not Yet`,
    accent: "#5A2D82",
    bg: "#F5EEFA",
    verses: [
    {
      label: `Anchor`,
      text: `He who testifies to these things says, 'Yes, I am coming soon.' Amen. Come, Lord Jesus.`,
      ref: `Revelation 22:20 — NIV`,
    },
    {
      label: `What We Will Be`,
      text: `Dear friends, now we are children of God, and what we will be has not yet been made known. But we know that when Christ appears, we shall be like him, for we shall see him as he is. All who have this hope in him purify themselves, just as he is pure.`,
      ref: `1 John 3:2–3 — NIV`,
    },
    {
      label: `Since Everything Will Be Destroyed`,
      text: `Since everything will be destroyed in this way, what kind of people ought you to be? You ought to live holy and godly lives as you look forward to the day of God and speed its coming.`,
      ref: `2 Peter 3:11–12 — NIV`,
    }
    ],
    revelation: [
    `The last prayer in the Bible is two words. Come, Lord Jesus. Maranatha — an Aramaic word so early that it was preserved untranslated even in the Greek-speaking church, which tells us something about how deep in the bone of the earliest Christians this longing was. They did not say it as a formula. They said it as people who had seen the risen Christ, who had received the Holy Spirit, who were living with one eye always on the horizon. Come. We are waiting. We are ready. Come.`,
    `The whole of this week has been building toward this. Hezekiah trusted God in crisis because he knew that the God who made heaven and earth had not abandoned His people. Ruth and Boaz lived in faithful, ordinary, costly hesed because that is what it looks like when people who know God let that knowledge shape their daily behaviour. Daniel prayed three times a day, oriented toward Jerusalem, because prayer was the expression of a life pointed toward God. Simeon and Anna waited with righteousness and devotion because the quality of your waiting is inseparable from the quality of your character. And now the week ends with 1 John 3:3, which ties all of it together in one sentence: all who have this hope in him purify themselves, just as he is pure.`,
    `The hope of Christ's return is not an escape from the responsibility of holy living. It is the most powerful motivation for it. 2 Peter 3:11 asks the most searching question: since everything will be destroyed, what kind of people ought you to be? The answer is not "it doesn't matter so enjoy yourself." The answer is: live holy and godly lives as you look forward to the day of God. The imminent return of Christ does not make your daily faithfulness irrelevant — it makes it urgently, cosmically significant. You are not just living your life. You are living a witness. You are living a testimony. You are living a prayer — the prayer that says with every faithful choice, every act of hesed, every hour of disciplined prayer, every day of righteous waiting: Come, Lord Jesus. Come.`
    ],
    prayers: [
    `Lord Jesus, I close this week with the oldest prayer of the church on my lips and in my heart: come. Come into the situations I have spread before You like Hezekiah spread his letter. Come into the ordinary faithfulness I am trying to practise like Ruth in the field. Come into the prayer life I am building like Daniel at his window. Come into the waiting I am learning to do like Simeon in the temple. Come.`,
    `I live between the already and the not yet — and I want to live that space well. You have already come — the incarnation, the cross, the resurrection, the ascension, the gift of the Holy Spirit. And You are coming again. In between, I have been given the extraordinary privilege of living in such a way that my life points to both. Every act of trust says: He is faithful. Every act of hesed says: His love is real. Every disciplined prayer says: He hears. Every day of holy waiting says: He is worth it.`,
    `Let this week have produced something in me that persists beyond Sunday. Not a spiritual high that fades by Tuesday but a deeper, quieter, more durable orientation toward You. I am Yours. I am watching. I am waiting. Come, Lord Jesus. Come.`
    ],
    amen: `Maranatha — Come, Lord Jesus. Amen.`,
    practices: [
    `Read Revelation 22:12–21 in full — the final words of Scripture. Note how many times the theme of coming appears, and how the response of the church to every promise of Christ's return is the same prayer: come. Let those last verses of the Bible be your prayer for the week ahead.`,
    `Review your journal from the whole week. Write one sentence that captures the central thing God said to you across all seven days. This is your testimony from this week. Keep it somewhere you will see it.`,
    `Identify how the four themes connected in your own life this week: where did you need Hezekiah's trust? Where did you see Ruth's providence? Where did you practise Daniel's prayer? Where did you identify with Simeon's waiting? Write it honestly.`,
    `Share something from this week with someone close to you. The word of your testimony is a weapon. The themes of this week — trust, providence, prayer, holy waiting — are things people around you need to hear. Be generous with what God has given you.`
    ],
  },
];

export default week_8;
