// AUTO-GENERATED by scripts/build-content.js
// Source: content/week-5/
// Do not edit this file directly — edit the .md files instead,
// then run:  node scripts/build-content.js

import type { DayContent } from "./types";

const week_5: DayContent[] = [
  {
    num: 1,
    abbr: "Mon",
    name: "Monday",
    title: `Poor in Spirit — Theirs Is the Kingdom`,
    theme: `The First Beatitude · The Hinge on Which Everything Turns`,
    accent: "#1A3A6E",
    bg: "#EBF1FA",
    verses: [
    {
      label: `Anchor`,
      text: `Blessed are the poor in spirit, for theirs is the kingdom of heaven.`,
      ref: `Matthew 5:3 — NIV`,
    },
    {
      label: `The Posture God Esteems`,
      text: `This is the one I esteem: he who is humble and contrite in spirit, and trembles at my word.`,
      ref: `Isaiah 66:2b — NIV`,
    },
    {
      label: `Counting Everything Loss`,
      text: `But whatever were gains to me I now consider loss for the sake of Christ. What is more, I consider everything a loss because of the surpassing worth of knowing Christ Jesus my Lord.`,
      ref: `Philippians 3:7–8 — NIV`,
    }
    ],
    revelation: [
    `Jesus opens the Sermon on the Mount — His manifesto for kingdom living — not with a command but with a declaration of blessedness. And He begins in the most unexpected place: poverty of spirit. Not wealth of spirit. Not spiritual achievement. Not religious performance. The very first quality He identifies as kingdom-qualifying is an emptiness, a bankruptcy before God — the recognition that you bring nothing to the table that could earn what only grace can give.`,
    `The Greek word translated "poor" here is ptochos — not simply lacking resources, but utterly destitute, crouching, completely dependent. To be poor in spirit is to arrive before God with no self-sufficiency, no résumé, no claim on His favour — and to know it. This is the posture Isaiah describes when God says: this is the one I esteem, the one who is humble and contrite. And Paul in Philippians captures what this looks like in practice: everything he achieved, every credential, every advantage — he counted it loss. Not because it was worthless in the world's eyes, but because knowing Christ made everything else comparative rubbish.`,
    `This is the hinge on which the entire Beatitudes turn. The cross is where this poverty of spirit was purchased for us. Christ became poor so that we might be rich — He emptied Himself so that in our emptiness, we might be filled with the fullness of God. Poverty of spirit is not a spiritual deficiency to be overcome. It is the open hand that receives everything the kingdom offers. And the promise is staggering: theirs is the kingdom of heaven. Not theirs will be. Theirs is — present tense, immediate, given now to the empty-handed.`
    ],
    prayers: [
    `Father, I begin this week doing what is hardest and most important: I arrive before You with empty hands. I bring no achievement to impress You, no spiritual performance to earn Your favour, no résumé that qualifies me for what only grace can give. I am poor in spirit — and I receive that not as failure but as the very posture that opens me to the kingdom.`,
    `Strip away every pretence of self-sufficiency I have been carrying. Every confidence in my own understanding, my own ability, my own track record. Let me see clearly that without You I have nothing, and that in You I lack nothing. This is the paradox of the kingdom — the empty are the full, the last are the first, the poor in spirit inherit everything.`,
    `Christ became poor so that I might be rich. He emptied Himself at the cross so that my emptiness could be filled. I receive that exchange today with both hands open.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Matthew 5:1–12 in full as an opening meditation on the whole week ahead. Let the Beatitudes land as a portrait rather than a checklist — this is what a transformed person looks like.`,
    `Read Philippians 3:3–11 — Paul's full accounting of what he considered gain and what he chose to count as loss. Journal: what is the gain in your own life that you have been treating as a qualification before God?`,
    `Spend 10 minutes in intentional silence before God — not asking for anything, not bringing any agenda. Simply arrive empty. Let poverty of spirit be an act of worship rather than a problem to be solved.`,
    `Read 2 Corinthians 8:9 — "Though he was rich, yet for your sake he became poor, so that you through his poverty might become rich." Meditate on the exchange the cross represents. Let it undo your self-reliance.`
    ],
  },

  {
    num: 2,
    abbr: "Tue",
    name: "Tuesday",
    title: `Mourning, Hunger & the Blood That Cleanses`,
    theme: `The Second & Fourth Beatitudes · Appetite Transformed by the Cross`,
    accent: "#7A1A1A",
    bg: "#FAF0F0",
    verses: [
    {
      label: `Anchor`,
      text: `Blessed are those who mourn, for they will be comforted. Blessed are those who hunger and thirst for righteousness, for they will be filled.`,
      ref: `Matthew 5:4, 6 — NIV`,
    },
    {
      label: `The Blood That Purifies`,
      text: `But if we walk in the light, as he is in the light, we have fellowship with one another, and the blood of Jesus, his Son, purifies us from all sin.`,
      ref: `1 John 1:7 — NIV`,
    },
    {
      label: `The Conscience Cleansed`,
      text: `How much more, then, will the blood of Christ, who through the eternal Spirit offered himself unblemished to God, cleanse our consciences from acts that lead to death, so that we may serve the living God!`,
      ref: `Hebrews 9:14 — NIV`,
    }
    ],
    revelation: [
    `The mourning Jesus speaks of in the second Beatitude is not grief over personal loss or difficult circumstances — it is mourning over sin. It is the response of a soul that has seen something of the holiness of God and something of its own condition in that light. This mourning is not despair — it is the grief of someone who genuinely cares. And it is precisely this mourning that the blood of Jesus was shed to address. When the conscience is pierced, when mourning arises over what we have done and who we have been, the blood of Christ is God's answer — not scolding, not distance, but comfort. They will be comforted.`,
    `Hebrews 9:14 makes an astonishing claim about the blood. It does not merely forgive — it cleanses the conscience. The guilt that sits in the deepest part of you — the memories that surface at night, the shame that has shaped how you see yourself — the blood of Christ has the power to reach that deep and clean it. Not cover it. Not manage it. Cleanse it. From acts that lead to death, so that we may serve the living God. The purpose of the cleansing is not just inner peace — it is restored capacity for purpose.`,
    `The fourth Beatitude — hunger and thirst for righteousness — speaks to transformed appetite. This is the natural fruit of having been cleansed by the blood: you begin to want what God wants. The person who has truly wept over their sin and received the comfort of forgiveness does not return to that sin easily. Their appetite has changed. They hunger now for what is right, what is true, what is holy — and the promise is that this hunger will be satisfied. They will be filled. God does not leave holy hunger unmet.`
    ],
    prayers: [
    `Lord Jesus, I come to You today with the grief that genuine faith produces — mourning over the ways I have fallen short, the sin that has separated me from the fullness of what You intended for me. I do not come in despair. I come in the confidence that this mourning is the very thing that draws Your comfort.`,
    `I apply the blood of Jesus over my conscience today. Not as a formula — as a faith-filled act of receiving what was purchased for me at immeasurable cost. Every charge that my own heart brings against me, every memory that tries to define me by my worst moments — I bring it under the covering of the blood. Cleanse me. Not just forgive — cleanse. So that I may serve You with a clear conscience and a free heart.`,
    `And awaken in me a genuine hunger and thirst for righteousness. Not performance. Not religion. Actual righteousness — the character of Christ, pressed into the fabric of my daily life. Let me want what You want. Let the appetites the world has cultivated in me be replaced by this one, clean, holy hunger. Fill me, Lord. I am empty and I am asking.`
    ],
    amen: `In the name of the One whose blood speaks a better word, Amen.`,
    practices: [
    `Read Hebrews 9:11–14 in full — the full argument for why the blood of Christ is categorically different from any other offering. Let the weight of "how much more" land on you personally.`,
    `Spend time in honest mourning before God — not manufactured emotion, but genuine acknowledgment of specific ways you have fallen short this past week. Name them. Then receive the comfort of 1 John 1:7 over each one.`,
    `Journal: "What do I currently hunger and thirst for? Does the answer reflect a transformed appetite — or the same appetites the world has shaped in me?" Ask God to realign your desires with His.`,
    `Read Psalm 51 — David's great prayer after sin, which moves from mourning to petition to purpose. Pray it as your own prayer today. Let verse 10 be your declaration: "Create in me a pure heart, O God."`
    ],
  },

  {
    num: 3,
    abbr: "Wed",
    name: "Wednesday",
    title: `The Meek, the Merciful & the Cross as Pattern`,
    theme: `The Third & Fifth Beatitudes · Power Under Submission, Mercy Freely Given`,
    accent: "#1A3A6E",
    bg: "#EBF1FA",
    verses: [
    {
      label: `Anchor`,
      text: `Blessed are the meek, for they will inherit the earth. Blessed are the merciful, for they will be shown mercy.`,
      ref: `Matthew 5:5, 7 — NIV`,
    },
    {
      label: `Clothed in the Cross's Character`,
      text: `Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience. Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.`,
      ref: `Colossians 3:12–13 — NIV`,
    },
    {
      label: `Rich in Mercy`,
      text: `But because of his great love for us, God, who is rich in mercy, made us alive with Christ even when we were dead in transgressions — it is by grace you have been saved.`,
      ref: `Ephesians 2:4–5 — NIV`,
    }
    ],
    revelation: [
    `Meekness is one of the most misunderstood words in the Christian vocabulary. It is consistently confused with weakness — with passivity, with the absence of will or strength. But the Greek word praus was used in the ancient world to describe a war horse that had been trained — an animal of enormous power that had learned to place that power under the rider's control. Meekness is not the absence of strength. It is strength under perfect submission.`,
    `Christ on the cross is the supreme definition of meekness. He who spoke galaxies into existence, He before whom every angel bowed — He allowed Himself to be nailed to wood. Not because He lacked the power to stop it. Because He chose submission to the Father's will over the exercise of His own. The cross is the most powerful act in all of history, and it was accomplished through the most complete meekness ever displayed. This is the model Colossians calls us to — not the meekness of the weak, but the meekness of those who have been so filled with the love of God that they no longer need to assert themselves at the expense of others.`,
    `Mercy flows from having received it. Ephesians 2 says God is rich in mercy — not reluctant, not transactional, but abundantly, lavishly merciful. And the person who has truly experienced that mercy — who has stood at the cross and understood the depth of what was extended to them — cannot help but extend it to others. The forgiveness in Colossians 3:13 — forgive as the Lord forgave you — is not a suggestion. It is the natural outflow of a life shaped by the cross. You were shown mercy while you were an enemy. What will you show to the people who have hurt you?`
    ],
    prayers: [
    `Lord Jesus, teach me Your meekness. Not the meekness of someone without will, but the meekness of someone whose will has been submitted so completely to the Father that they no longer need to fight for themselves. You stood before Pilate with the power to end the world — and You said nothing. That silence was not weakness. It was the most powerful thing anyone has ever done.`,
    `And teach me the mercy that flows from the cross. I confess that I find mercy easy in the abstract and difficult in the particular — especially toward those who have wounded me most. But when I stand at the cross and receive what was given to me while I was still Your enemy, how can I withhold it from anyone? Let the depth of what I have received be the measure of what I give.`,
    `Clothe me today — with compassion, kindness, humility, gentleness, patience. Not as a performance of Christian virtue, but as the natural garments of a person who has been so loved by God that love has become their reflex.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Numbers 12:3 — "Moses was a very humble man, more humble than anyone else on the face of the earth." Then read Numbers 12:1–8 for context. Moses held enormous authority. Reflect on the relationship between meekness and true, lasting influence.`,
    `Identify one person toward whom you have been withholding mercy — consciously or not. Pray for them specifically today. Ask God to give you the capacity to extend what you yourself have received.`,
    `Read the parable of the unmerciful servant in Matthew 18:21–35. Let the contrast between the debt cancelled and the debt withheld be a mirror for your own life. Ask: which servant am I in this story right now?`,
    `Journal: "What would genuine meekness look like in the most difficult relationship in my life right now? What strength would I need to put under submission — and what would be the fruit of doing so?"`
    ],
  },

  {
    num: 4,
    abbr: "Thu",
    name: "Thursday",
    title: `Pure in Heart & Peacemakers`,
    theme: `The Sixth & Seventh Beatitudes · The Blood Makes Purity Possible`,
    accent: "#7A1A1A",
    bg: "#FAF0F0",
    verses: [
    {
      label: `Anchor`,
      text: `Blessed are the pure in heart, for they will see God. Blessed are the peacemakers, for they will be called children of God.`,
      ref: `Matthew 5:8–9 — NIV`,
    },
    {
      label: `The Open Way`,
      text: `Therefore, brothers and sisters, since we have confidence to enter the Most Holy Place by the blood of Jesus, by a new and living way opened for us through the curtain, that is, his body... let us draw near to God with a sincere heart and with the full assurance that faith brings, having our hearts sprinkled to cleanse us from a guilty conscience.`,
      ref: `Hebrews 10:19–20, 22 — NIV`,
    },
    {
      label: `Ambassadors of Reconciliation`,
      text: `All this is from God, who reconciled us to himself through Christ and gave us the ministry of reconciliation... We are therefore Christ's ambassadors, as though God were making his appeal through us.`,
      ref: `2 Corinthians 5:18, 20 — NIV`,
    }
    ],
    revelation: [
    `Blessed are the pure in heart, for they will see God. This promise is breathtaking — and impossibly demanding if we have to meet it ourselves. Who can claim purity of heart? Who has a heart with no hidden motives, no double vision, no divided loyalty? The answer is: no one — except by the blood of Jesus. Hebrews 10 makes the remarkable claim that our hearts can be sprinkled to cleanse us from a guilty conscience. The blood of Christ reaches the interior — not just the external behaviour but the heart itself, making possible what no human effort could achieve: genuine, interior purity.`,
    `And the promise attached to purity of heart is the most intimate of all the Beatitudes: they will see God. Not see about God. Not hear about God. See Him. This is the telos — the ultimate destination — of the entire Christian life. Every act of confession, every act of repentance, every choice of holiness, every moment of trust in difficulty — all of it is oriented toward this: a heart so purified by the blood that it can see clearly, without obstruction, the face of the One it was made for.`,
    `The seventh Beatitude — peacemakers — flows naturally from having received the ministry of reconciliation. You were made peace with God through the cross. That reconciliation was given to you. And now it becomes your ministry. 2 Corinthians 5 makes the staggering claim that God makes His appeal through you — that when you work to restore broken relationships, to bring peace where there is conflict, to reconcile what has been divided, you are carrying out the very work that Christ accomplished at Golgotha. You are not just doing good. You are being what you were made to be: a child of God.`
    ],
    prayers: [
    `Father, I want to see You. Not just know about You — see You. And I understand today that purity of heart is the precondition for that vision. So I come to the blood of Jesus and ask that what no willpower of mine could achieve, the cross might accomplish: a heart made clean, a conscience made clear, an interior life free from the double vision of divided loyalties.`,
    `Sprinkle my heart clean today. Not by my discipline alone, but by the power of what was poured out at Calvary. Let there be nothing in me that prevents me from seeing You clearly. Remove the cataracts of unconfessed sin, the fog of distraction, the cloudiness of a heart that has been looking in too many directions at once. I want to see You.`,
    `And make me a peacemaker. Not a conflict-avoider — a peacemaker. Someone who actively, intentionally carries the reconciling work of the cross into the broken relationships and divided communities around me. Let Your appeal come through me. Let the world see, in the way I make peace, what it looks like to be a child of God.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Psalm 24:3–4 — "Who may ascend the mountain of the Lord? The one who has clean hands and a pure heart." Then read Hebrews 10:19–22 as God's own answer to that requirement. Let the two passages speak to each other.`,
    `Identify one relationship in your life that is currently marked by conflict, distance, or unresolved tension. Pray specifically about it today. Ask God how He is calling you to be a peacemaker — not just a peace-keeper — in that situation.`,
    `Journal: "What are the divided loyalties in my heart right now — the places where I am trying to see God and something else at the same time?" Bring each one honestly to the blood of Jesus.`,
    `Read 2 Corinthians 5:14–21 in full — Paul's complete theology of reconciliation. Let "we are therefore Christ's ambassadors" become not an abstract idea but a present-tense identity you carry into your day.`
    ],
  },

  {
    num: 5,
    abbr: "Fri",
    name: "Friday",
    title: `Blessed Are the Persecuted`,
    theme: `The Eighth Beatitude · The Blood Speaks a Better Word Than Accusation`,
    accent: "#1A3A6E",
    bg: "#EBF1FA",
    verses: [
    {
      label: `Anchor`,
      text: `Blessed are those who are persecuted because of righteousness, for theirs is the kingdom of heaven. Blessed are you when people insult you, persecute you and falsely say all kinds of evil against you because of me. Rejoice and be glad, because great is your reward in heaven.`,
      ref: `Matthew 5:10–12 — NIV`,
    },
    {
      label: `Overcome by the Blood`,
      text: `They triumphed over him by the blood of the Lamb and by the word of their testimony; they did not love their lives so much as to shrink from death.`,
      ref: `Revelation 12:11 — NIV`,
    },
    {
      label: `Who Can Bring a Charge?`,
      text: `Who will bring any charge against those whom God has chosen? It is God who justifies. Who then is the one who condemns? No one. Christ Jesus who died — more than that, who was raised to life — is at the right hand of God and is also interceding for us.`,
      ref: `Romans 8:33–34 — NIV`,
    }
    ],
    revelation: [
    `The final Beatitude is the most surprising — and perhaps the most revealing. Jesus does not conclude His portrait of the blessed life with health, wealth, or the absence of difficulty. He concludes it with persecution. A life genuinely shaped by the Beatitudes — poor in spirit, mourning over sin, meek, hungry for righteousness, merciful, pure in heart, making peace — will become visible. And visible light draws opposition. The world does not persecute irrelevance. It persecutes what it recognises as a genuine alternative to itself.`,
    `The blood of Jesus is the specific weapon against accusation. Romans 8:33–34 asks two rhetorical questions that demolish every charge the enemy can bring: Who will bring any charge against those whom God has chosen? God justifies. Who then condemns? Christ died. Christ rose. Christ intercedes. Every accusation — whether from the enemy, from your own conscience, or from people who misrepresent you — runs headlong into the blood of Jesus, which speaks a better word. The blood does not merely silence the accusation. It answers it permanently, legally, finally.`,
    `Revelation 12:11 gives the overcomer's threefold weapon: the blood of the Lamb, the word of their testimony, and a willingness to lay down self-preservation. Your testimony — the story of what God has done in your life — is itself a weapon in spiritual warfare. When you speak of what Christ has accomplished in you, you are wielding the blood in narrative form. The persecution confirms your alignment with the kingdom. The blood secures your standing in it. And the promise echoes the very first Beatitude: theirs is the kingdom of heaven. The first and the last Beatitude end in exactly the same place.`
    ],
    prayers: [
    `Lord Jesus, I receive today the counterintuitive blessing of the persecuted. I do not ask for persecution — but I ask for the kind of visible, genuine, costly faith that makes it possible. Let my life be bright enough to draw opposition. Let my alignment with the kingdom be clear enough that the world knows whose side I am on.`,
    `And when the accusations come — from without and from within — I take my stand on the blood of Jesus. Who can bring a charge against me? God has justified me. Who condemns? Christ died. Christ rose. Christ intercedes for me at the right hand of the Father right now, at this very moment. No accusation survives that defence. I am not defined by what people say about me. I am defined by what the blood says about me.`,
    `I take up my testimony today as a weapon. The story of what You have done in my life is not a private comfort — it is a public declaration of Your faithfulness. Let me speak it with confidence, knowing that when I testify to Your goodness, I am participating in the very victory that Revelation 12:11 describes.`
    ],
    amen: `In the overcoming name of Jesus, Amen.`,
    practices: [
    `Read Hebrews 12:24 — "to Jesus the mediator of a new covenant, and to the sprinkled blood that speaks a better word than the blood of Abel." Meditate on what it means that the blood of Jesus speaks — and what it says over your life specifically today.`,
    `Identify any accusation — from others, from the enemy, or from your own conscience — that you have been believing about yourself. Bring it to Romans 8:33–34. Speak those two questions aloud. Let the blood answer each one.`,
    `Write out your testimony in one paragraph — what God has done in your life, specifically and personally. This is your weapon. Practise using it: share it with one person today.`,
    `Read Acts 5:41 — "The apostles left the Sanhedrin, rejoicing because they had been counted worthy of suffering disgrace for the Name." Pray for the grace to see opposition as confirmation rather than contradiction.`
    ],
  },

  {
    num: 6,
    abbr: "Sat",
    name: "Saturday",
    title: `Walking in the Fullness of God's Purpose`,
    theme: `Purpose · The Beatitudes as a Portrait of a Person Living on Purpose`,
    accent: "#1E5C3A",
    bg: "#EBF5EF",
    verses: [
    {
      label: `Anchor`,
      text: `For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.`,
      ref: `Ephesians 2:10 — NIV`,
    },
    {
      label: `Plans to Prosper`,
      text: `For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.`,
      ref: `Jeremiah 29:11 — NIV`,
    },
    {
      label: `Predestined to Be Conformed`,
      text: `For those God foreknew he also predestined to be conformed to the image of his Son, that he might be the firstborn among many brothers and sisters. And those he predestined, he also called; those he called, he also justified; those he justified, he also glorified.`,
      ref: `Romans 8:29–30 — NIV`,
    }
    ],
    revelation: [
    `Having spent five days sitting with the Beatitudes and the blood of Jesus, we arrive at Saturday with a question that the whole week has been building toward: what is all of this for? The answer is both simpler and more expansive than we often think. The purpose of the Christian life is not primarily what you do — it is who you become. And Romans 8:29 names that becoming with extraordinary precision: conformed to the image of His Son.`,
    `The Beatitudes are not a programme for spiritual improvement. They are a portrait of a person who looks like Jesus. Poor in spirit — like Christ who emptied Himself. Mourning over sin — like Christ who wept over Jerusalem. Meek — like Christ who submitted to the cross. Hungry for righteousness — like Christ whose food was to do the Father's will. Merciful — like Christ who forgave from the cross. Pure in heart — like Christ who had no sin. A peacemaker — like Christ who is our peace. Persecuted for righteousness — like Christ who was crucified for it. The Beatitudes are the character of Jesus, reproduced in those who have been transformed by His cross and His blood.`,
    `Ephesians 2:10 says the works were prepared in advance — and they were prepared for a person of this character. You do not find your purpose and then develop the character to fulfil it. You develop the character, and the purpose becomes clear. Jeremiah 29:11 is a promise of plans — but it is a promise made to people in exile, in difficulty, in the middle of circumstances that made the future look impossible. The purpose of God is not deterred by your current circumstances. It was settled before time, secured by the cross, and is being worked out in the very process of your being conformed to the image of Christ.`
    ],
    prayers: [
    `Father, I receive today the clarity that this week has been building toward. My purpose is not primarily a role to play or a platform to build or a career to construct. My purpose is to be conformed to the image of Your Son — and from that conformity, to walk in the specific good works You have prepared for me before the foundation of the world.`,
    `I look at the Beatitudes this morning and I see Jesus. Poor in spirit, meek, merciful, pure, a peacemaker, willing to be persecuted for righteousness. This is who the cross is making me. Slowly, sometimes painfully, always faithfully — You are pressing the image of Your Son into the clay of my life. Do not stop. Even where it hurts. Especially where it hurts.`,
    `And I trust the plans You have for me. Not because they are always comfortable or always clear, but because they come from You — and You have proven Your faithfulness at the cross. The God who did not spare His own Son in order to secure my purpose will not now abandon that purpose when the circumstances look uncertain.`
    ],
    amen: `In Jesus' name, Amen.`,
    practices: [
    `Read Romans 8:28–30 slowly and carefully. Notice the golden chain: foreknew → predestined → called → justified → glorified. Where are you in that chain today? How does knowing where it ends change how you face the present?`,
    `Look back at the Beatitudes as a whole — Matthew 5:3–12. Place your name mentally in each one. Which qualities are already visible in you? Which are still being formed? Journal honestly about both.`,
    `Identify one good work — from Ephesians 2:10 — that you sense God has specifically prepared for you in this season. Name it as concretely as you can. Then ask: what character quality from the Beatitudes does this work require of me?`,
    `Read Colossians 1:27 — "Christ in you, the hope of glory." Let this be your purpose statement for the week ahead. Not what you do, but Who is in you and what He is becoming through you.`
    ],
  },

  {
    num: 7,
    abbr: "Sun",
    name: "Sunday",
    title: `Salt, Light & the Sending`,
    theme: `The Week's Culmination · You Are What the Cross Has Made You`,
    accent: "#BF8B3A",
    bg: "#FAF3E0",
    verses: [
    {
      label: `Anchor`,
      text: `You are the salt of the earth... You are the light of the world. A town built on a hill cannot be hidden... let your light shine before others, that they may see your good deeds and glorify your Father in heaven.`,
      ref: `Matthew 5:13–14, 16 — NIV`,
    },
    {
      label: `The Blood That Speaks`,
      text: `To Jesus the mediator of a new covenant, and to the sprinkled blood that speaks a better word than the blood of Abel.`,
      ref: `Hebrews 12:24 — NIV`,
    },
    {
      label: `Made to Be a Kingdom`,
      text: `To him who loves us and has freed us from our sins by his blood, and has made us to be a kingdom and priests to serve his God and Father — to him be glory and power for ever and ever!`,
      ref: `Revelation 1:5b–6 — NIV`,
    }
    ],
    revelation: [
    `Immediately after the Beatitudes, Jesus speaks two declarations that are easy to miss in their grammatical structure. He does not say: try to be salt. He does not say: you should become the light of the world. He says: you are the salt of the earth. You are the light of the world. These are statements of identity, not instructions for behaviour. The Beatitudes describe what you are becoming through the work of the cross; salt and light describe what you therefore are in the world — not what you must strive to achieve, but what you already are when the cross has done its work.`,
    `Revelation 1:5–6 ties the blood and the identity together with breathtaking clarity. By His blood, you have been freed from your sins. And by that same act, you have been made something: a kingdom, a priest, someone who serves the living God. The blood is not only redemptive — it is constitutive. It does not merely remove what was wrong. It establishes what you now are. You have been made to be a kingdom. You carry within you the reign of God everywhere you go.`,
    `The closing word of the Beatitudes section is commission: let your light shine before others, that they may see your good deeds and glorify your Father in heaven. Notice the ultimate purpose — not that they will glorify you, not even that they will glorify your good works, but that they will glorify your Father in heaven. The whole architecture of the Beatitudes, the cross, the blood, the purpose — it is all oriented toward this: a world that looks at lives transformed by the grace of God and is moved to worship the One who made that transformation possible. This is the purpose you were made for. Go and live it.`
    ],
    prayers: [
    `Father, I close this week not with a sense of arrival but with a sense of sending. I have sat with the Beatitudes — and I have seen in them a portrait of Jesus, and a portrait of who I am being made into by the power of the cross. I have stood at the blood and received what it purchased: freedom, cleansing, a new identity, an open way into Your presence.`,
    `I go into this coming week as salt — not trying to be salty, but carrying in myself the preserving, flavour-giving character of a life shaped by the kingdom. I go as light — not performing visibility, but shining with the natural luminosity of someone in whom Christ lives. The Beatitudes are not goals I am pursuing. They are the shape that Your grace is pressing into me, day by day, through every difficult circumstance and every quiet act of obedience.`,
    `Let my life this week point people to You. Let them see something in me — in my meekness, my mercy, my purity of intention, my willingness to make peace — that they cannot explain apart from God. And let the only explanation they can find be the right one: that I have been with Jesus, covered by His blood, and shaped by His character. To Him be glory and power for ever and ever.`
    ],
    amen: `Amen.`,
    practices: [
    `Review the whole week — which Beatitude landed most deeply for you? Which one feels most like the area where God is currently doing His most significant work? Write it down and carry it into the month ahead.`,
    `The blood of Jesus appeared throughout this week — cleansing, speaking, overcoming, making you a kingdom and priest. Write one sentence that captures what the blood means to you personally, in your own words. Return to it whenever accusation rises.`,
    `Share one insight from this week with someone close to you. The word of your testimony is a weapon. Use it deliberately and generously.`,
    `Read Matthew 5:1–16 in one sitting as a closing meditation — from the Beatitudes to salt and light. Let it be a mirror. Let it be a map. Let it send you.`
    ],
  },
];

export default week_5;
